src/api/config/routes.rb
# we take everything here that is not XML - the default mimetype is xml though
class WebuiMatcher
  class InvalidRequestFormat < APIException
  end

  def self.matches?(request)
    request.format.to_sym != :xml
  rescue ArgumentError => e
    raise InvalidRequestFormat, e.to_s
  end
end

# here we take everything that is XML, JSON or osc ;)
class APIMatcher
  def self.matches?(request)
    format = request.format.to_sym || :xml
    format == :xml || format == :json || public_or_about_path?(request)
  end

  def self.public_or_about_path?(request)
    request.fullpath.start_with?('/public', '/about')
  end
end

OBSApi::Application.routes.draw do
  mount Peek::Railtie => '/peek'

  cons = {
    arch:         %r{[^\/]*},
    binary:       %r{[^\/]*},
    filename:     %r{[^\/]*},
    id:           %r{\d*},
    login:        %r{[^\/]*},
    package:      %r{[^\/]*},
    package_name: %r{[^\/]*},
    project:      %r{[^\/]*},
    project_name: %r{[^\/]*},
    repository:   %r{[^\/]*},
    service:      %r{\w[^\/]*},
    title:        %r{[^\/]*},
    user:         %r{[^\/]*}
  }

  constraints(WebuiMatcher) do
    root 'webui/main#index'

    controller 'webui/main' do
      get 'main/systemstatus' => :systemstatus
      get 'main/add_news_dialog' => :add_news_dialog
      post 'main/add_news' => :add_news
      get 'main/delete_message_dialog' => :delete_message_dialog
      post 'main/delete_message' => :delete_message
    end

    controller 'webui/feeds' do
      get 'main/news' => :news, constraints: ->(req) { req.format == :rss }, as: :news_feed
      get 'main/latest_updates' => :latest_updates, constraints: ->(req) { req.format == :rss }, as: :latest_updates_feed
      get 'project/latest_commits/:project' => :commits, defaults: { format: 'atom' }, constraints: cons, as: 'commits_feed'
      get 'user/feed/:token' => :notifications, defaults: { format: 'rss' }, as: :user_rss_notifications
    end

    resources :attribs, constraints: cons, only: [:create, :update, :destroy], controller: 'webui/attribute' do
      collection do
        get ':project(/:package)/new' => :new, constraints: cons, as: 'new'
        get ':project(/:package)/:attribute/edit' => :edit, constraints: cons, as: 'edit'
        get ':project(/:package)' => :index, constraints: cons, as: 'index', defaults: { format: 'html' }
      end
    end

    resources :image_templates, constraints: cons, only: [:index], controller: 'webui/image_templates'

    resources :download_repositories, constraints: cons, only: [:create, :update, :destroy], controller: 'webui/download_on_demand'

    controller 'webui/configuration' do
      get 'configuration' => :index
      patch 'configuration' => :update
      get 'configuration/interconnect' => :interconnect
      post 'configuration/interconnect' => :create_interconnect
    end

    controller 'webui/subscriptions' do
      get 'notifications' => :index
      put 'notifications' => :update
    end

    controller 'webui/architectures' do
      get 'architectures' => :index
      patch 'architectures/bulk_update_availability' => :bulk_update_availability, as: 'bulk_update_availability'
    end

    controller 'webui/monitor' do
      get 'monitor/' => :index
      get 'monitor/old' => :old
      get 'monitor/update_building' => :update_building
      get 'monitor/events' => :events
    end

    defaults format: 'html' do
      controller 'webui/package' do
        get 'package/show/:project/:package' => :show, as: 'package_show', constraints: cons
        get 'package/dependency/:project/:package' => :dependency, constraints: cons
        get 'package/binary/:project/:package' => :binary, constraints: cons, as: 'package_binary'
        get 'package/binaries/:project/:package' => :binaries, constraints: cons, as: 'package_binaries'
        get 'package/users/:project/:package' => :users, as: 'package_users', constraints: cons
        get 'package/requests/:project/:package' => :requests, as: 'package_requests', constraints: cons
        get 'package/statistics/:project/:package' => :statistics, as: 'package_statistics', constraints: cons
        get 'package/commit/:project/:package' => :commit, as: 'package_commit', constraints: cons
        get 'package/revisions/:project/:package' => :revisions, constraints: cons, as: 'package_view_revisions'
        post 'package/submit_request/:project/:package' => :submit_request, constraints: cons
        get 'package/add_person/:project/:package' => :add_person, constraints: cons
        get 'package/add_group/:project/:package' => :add_group, constraints: cons
        get 'package/rdiff/:project/:package' => :rdiff, constraints: cons, as: 'package_rdiff'
        post 'package/save_new/:project' => :save_new, constraints: cons
        post 'package/branch' => :branch, constraints: cons
        post 'package/save/:project/:package' => :save, constraints: cons
        post 'package/remove/:project/:package' => :remove, constraints: cons
        get 'package/add_file/:project/:package' => :add_file, constraints: cons
        post 'package/save_file/:project/:package' => :save_file, constraints: cons
        post 'package/remove_file/:project/:package' => :remove_file, constraints: cons
        post 'package/save_person/:project/:package' => :save_person, constraints: cons
        post 'package/save_group/:project/:package' => :save_group, constraints: cons
        post 'package/remove_role/:project/:package' => :remove_role, constraints: cons
        get 'package/view_file/:project/:package/(:filename)' => :view_file, constraints: cons, as: 'package_view_file'
        get 'package/live_build_log/:project/:package/:repository/:arch' => :live_build_log, constraints: cons, as: 'package_live_build_log'
        defaults format: 'js' do
          get 'package/linking_packages/:project/:package' => :linking_packages, constraints: cons
          get 'package/update_build_log/:project/:package/:repository/:arch' => :update_build_log, constraints: cons
          get 'package/submit_request_dialog/:project/:package' => :submit_request_dialog, constraints: cons
          get 'package/delete_dialog/:project/:package' => :delete_dialog, constraints: cons
          post 'package/trigger_rebuild/:project/:package' => :trigger_rebuild, constraints: cons
          get 'package/abort_build/:project/:package' => :abort_build, constraints: cons
          post 'package/trigger_services/:project/:package' => :trigger_services, constraints: cons
          delete 'package/wipe_binaries/:project/:package' => :wipe_binaries, constraints: cons
        end
        get 'package/devel_project/:project/:package' => :devel_project, constraints: cons
        get 'package/buildresult' => :buildresult, constraints: cons
        get 'package/rpmlint_result' => :rpmlint_result, constraints: cons
        get 'package/rpmlint_log' => :rpmlint_log, constraints: cons
        get 'package/meta/:project/:package' => :meta, constraints: cons, as: 'package_meta'
        post 'package/save_meta/:project/:package' => :save_meta, constraints: cons
        # compat route
        get 'package/attributes/:project/:package', to: redirect('/attribs/%{project}/%{package}'), constraints: cons
        get 'package/edit/:project/:package' => :edit, constraints: cons, as: :package_edit
        # compat routes
        get 'package/repositories/:project/:package', to: redirect('/repositories/%{project}/%{package}'), constraints: cons
        get 'package/import_spec/:project/:package' => :import_spec, constraints: cons
        # compat route
        get 'package/files/:project/:package' => :show, constraints: cons
      end
    end

    resources :packages, only: [], param: :name do
      resource :job_history, controller: 'webui/packages/job_history', only: [] do
        get '/:project/:repository/:arch' => :index, as: :index, constraints: cons
      end

      resource :build_reason, controller: 'webui/packages/build_reason', only: [] do
        get '/:project/:repository/:arch' => :index, as: :index, constraints: cons
      end
    end

    controller 'webui/patchinfo' do
      post 'patchinfo/new_patchinfo' => :new_patchinfo
      post 'patchinfo/updatepatchinfo' => :updatepatchinfo
      get 'patchinfo/edit_patchinfo' => :edit_patchinfo
      get 'patchinfo/show/:project/:package' => :show, as: 'patchinfo_show', constraints: cons, defaults: { format: 'html' }
      get 'patchinfo/read_patchinfo' => :read_patchinfo
      post 'patchinfo/save' => :save
      post 'patchinfo/remove' => :remove
      get 'patchinfo/new_tracker' => :new_tracker
      get 'patchinfo/delete_dialog' => :delete_dialog
    end
    #
    controller 'webui/repositories' do
      get 'repositories/:project(/:package)' => :index, constraints: cons, as: 'repositories', defaults: { format: 'html' }
      get 'project/repositories/:project' => :index, constraints: cons, as: 'project_repositories'
      get 'project/add_repository/:project' => :new, constraints: cons
      get 'project/add_repository_from_default_list/:project' => :distributions, constraints: cons, as: :repositories_distributions
      post 'project/save_repository' => :create
      post 'project/update_target/:project' => :update, constraints: cons
      get 'project/repository_state/:project/:repository' => :state, constraints: cons, as: 'project_repository_state'
      post 'project/remove_target' => :destroy
      post 'project/create_dod_repository' => :create_dod_repository
      post 'project/create_image_repository' => :create_image_repository

      # Flags
      put 'flag/:project(/:package)' => :toggle_flag, constraints: cons
      post 'flag/:project(/:package)' => :create_flag, constraints: cons
      delete 'flag/:project(/:package)/:flag' => :remove_flag, constraints: cons
    end

    controller 'webui/kiwi/images' do
      get 'package/:package_id/kiwi_images/import_from_package' => :import_from_package, as: 'import_kiwi_image'
    end

src/api/app/controllers/webui/apidocs_controller.rb
class Webui::ApidocsController < Webui::WebuiController
  def index
    filename = File.expand_path(CONFIG['apidocs_location']) + '/index.html'
    if File.exist?(filename)
      render file: filename, formats: [:html]
    else
      logger.error "Unable to load apidocs index file from #{CONFIG['apidocs_location']}. Did you create the apidocs?"
      flash[:error] = 'Unable to load API documentation.'
      redirect_back(fallback_location: root_path)
    end
  end

  def file
    # Ensure it really is just a file name, no '/..', etc.
    filename = File.basename(params[:filename])
    file = File.expand_path(File.join(CONFIG['schema_location'], filename))
    if File.exist?(file)
      send_file(file, type: 'text/xml', disposition: 'inline')
    else
      flash[:error] = "File not found: #{params[:filename]}"
      redirect_back(fallback_location: { controller: 'apidocs', action: 'index' })
    end
    return
  end
end

src/api/app/controllers/webui/architectures_controller.rb
# Enabling/Disabling default architectures
class Webui::ArchitecturesController < Webui::WebuiController
  before_action :require_admin

  def index
    @architectures = Architecture.order(:name)
  end

  def bulk_update_availability
    all_valid = true
    params[:archs].each do |name, value|
      arch = Architecture.find_by(name: name)
      arch.available = value
      all_valid &&= arch.save
    end

    ::Configuration.write_to_backend

    respond_to do |format|
      if all_valid
        format.html { redirect_to architectures_path, notice: 'Architectures successfully updated.' }
      else
        format.html { redirect_back(fallback_location: root_path, error: 'Not all architectures could be saved') }
      end
    end
  end
end

src/api/app/controllers/webui/attribute_controller.rb
class Webui::AttributeController < Webui::WebuiController
  helper :all
  before_action :set_container, only: [:index, :new, :edit]
  before_action :set_attribute, only: [:update, :destroy]

  # raise an exception if authorize has not yet been called.
  after_action :verify_authorized, except: :index

  helper 'webui/project'

  def index
    @attributes = @container.attribs
  end

  def new
    if @package
      @attribute = Attrib.new(package_id: @package.id)
    else
      @attribute = Attrib.new(project_id: @project.id)
    end
    authorize @attribute, :create?
  end

  def edit
    @attribute = Attrib.find_by_container_and_fullname(@container, params[:attribute])

    authorize @attribute

    return unless @attribute.attrib_type.value_count && (@attribute.attrib_type.value_count > @attribute.values.length)
    (@attribute.attrib_type.value_count - @attribute.values.length).times { @attribute.values.build(attrib: @attribute) }
  end

  def create
    @attribute = Attrib.new(attrib_params)

    authorize @attribute

    # build the default values
    if @attribute.attrib_type.value_count
      @attribute.attrib_type.value_count.times do
        @attribute.values.build(attrib: @attribute)
      end
    end

    if @attribute.save
      if @attribute.values_editable?
        redirect_to edit_attribs_path(project: @attribute.project.to_s, package: @attribute.package.to_s,
                                      attribute: @attribute.fullname),
                    notice: 'Attribute was successfully created.'
      else
        redirect_to index_attribs_path(project: @attribute.project.to_s, package: @attribute.package.to_s),
                    notice: 'Attribute was successfully created.'
      end
    else
      redirect_back(fallback_location: root_path, error: "Saving attribute failed: #{@attribute.errors.full_messages.join(', ')}")
    end
  end

  def update
    authorize @attribute

    if @attribute.update(attrib_params)
      redirect_to edit_attribs_path(project: @attribute.project.to_s, package: @attribute.package.to_s, attribute: @attribute.fullname),
                  notice: 'Attribute was successfully updated.'
    else
      redirect_back(fallback_location: root_path, error: "Updating attribute failed: #{@attribute.errors.full_messages.join(', ')}")
    end
  end

  def destroy
    authorize @attribute

    @attribute.destroy
    redirect_back(fallback_location: root_path, notice: 'Attribute sucessfully deleted!')
  end

  private

  def set_container
    required_parameters :project
    begin
      @project = Project.get_by_name(params[:project])
    rescue APIException
      flash[:error] = "Project not found: #{params[:project]}"
      redirect_to(controller: 'project') && return
    end
    if params[:package]
      begin
        @package = Package.get_by_project_and_name(params[:project], params[:package], use_source: false)
      rescue APIException
        redirect_to(project_show_path(@project.to_s), error: "Package #{params[:package]} not found") && (return)
      end
      @container = @package
    else
      @container = @project
    end
  end

  def set_attribute
    @attribute = Attrib.find(params[:id])
    if @attribute.container.instance_of? Package
      @package = @attribute.container
      @project = @package.project
    elsif @attribute.container.instance_of? Project
      @project = @attribute.container
    end
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def attrib_params
    params.require(:attrib).permit(:attrib_type_id, :project_id, :package_id,
                                   values_attributes: [:id, :value, :position, :_destroy],
                                   issues_attributes: [:id, :name, :issue_tracker_id, :_destroy])
  end
end

src/api/app/controllers/webui/cloud/configurations_controller.rb
module Webui
  module Cloud
    class ConfigurationsController < WebuiController
      before_action :set_breadcrumb

      def index
        @crumb_list.push << 'Configuration'
      end

      private

      def set_breadcrumb
        @crumb_list = [WebuiController.helpers.link_to('Cloud Upload', cloud_upload_index_path)]
      end
    end
  end
end

src/api/app/controllers/webui/cloud/ec2/configurations_controller.rb
module Webui
  module Cloud
    module Ec2
      class ConfigurationsController < WebuiController
        before_action :require_login
        before_action :set_breadcrumb
        before_action -> { feature_active?(:cloud_upload) }

        def show
          @crumb_list << 'EC2'
          @ec2_configuration = User.current.ec2_configuration || User.current.create_ec2_configuration
          @aws_account_id = CONFIG['aws_account_id']
        end

        def update
          @ec2_configuration = User.current.ec2_configuration
          if @ec2_configuration.update(permitted_params)
            flash[:success] = 'Successfully updated your EC2 configuration.'
            redirect_to cloud_upload_index_path
          else
            flash[:error] = "Failed to updated your EC2 configuration: #{@ec2_configuration.errors.full_messages.to_sentence}."
            redirect_back(fallback_location: root_path)
          end
        end

        private

        def set_breadcrumb
          @crumb_list = [
            WebuiController.helpers.link_to('Cloud Upload', cloud_upload_index_path),
            WebuiController.helpers.link_to('Configuration', cloud_configuration_index_path)
          ]
        end

        def permitted_params
          params.require(:ec2_configuration).permit(:id, :arn)
        end
      end
    end
  end
end

src/api/app/controllers/webui/image_templates_controller.rb
class Webui::ImageTemplatesController < Webui::WebuiController
  before_action -> { feature_active?(:image_templates) }

  def index
    @projects = Project.image_templates

    respond_to do |format|
      format.html
      format.xml
    end
  end
end

src/api/app/views/webui/project/_buildstatus.html.haml
#project-buildstatus
  - if buildresults.blank?
    - if project.remoteurl
      %p
        %i This project is just used to get referenced for using remote resources.
    - elsif project.repositories.empty?
      %p
        %i
          This project currently has
          no #{link_to 'build targets', controller: :repositories, action: :distributions, project: project.name}
          defined.
    - else
      %p
        %i No build result available
  - else
    %table.repostatus
      - buildresults.each do |repository, builds|
        - builds.sort_by(&:architecture).each_with_index do |build, index|
          %tr
            - if index.zero?
              %td.repo{ rowspan: builds.length }
                = link_to(word_break(repository, 12),
                  { action: :state,
                    project: project.name,
                    repository: repository,
                    controller: :repositories },
                  { title: "Repository #{repository}" })

            %td.arch{ title: "#{repository} summary" }
              = repo_status_icon(build.state, build.details)
              = link_to(build.architecture, { action: :monitor,
                                              "#{valid_xml_id('repo_' + repository)}": 1,
                                              "arch_#{build.architecture}": 1,
                                              project: project.name,
                                              succeeded: 1,
                                              failed: 1,
                                              unresolvable: 1,
                                              broken: 1,
                                              blocked: 1,
                                              dispatching: 1,
                                              scheduled: 1,
                                              building: 1,
                                              finished: 1,
                                              signing: 1,
                                              locked: 1,
                                              deleting: 1,
                                              defaults: 0 }, rel: 'nofollow', class: 'nowrap')

            %td.nowrap{ style: "width: 1%" }
              - build.summary.each do |status_count|
                %span{ class: "status_#{status_count.code.to_s.gsub(/[- ]/, '_')}" }
                  = link_to("#{status_count.code}: #{status_count.count}",
                    { action: :monitor,
                      "#{valid_xml_id('repo_' + repository)}": 1,
                      "arch_#{build.architecture}": 1,
                      project: params[:project],
                      "#{status_count.code}": 1,
                      defaults: 0 }, rel: 'nofollow', class: 'nowrap')

                  = sprite_tag('help', title: Buildresult.status_description(status_count.code))
                %br

src/api/app/views/webui/project/_category_selection.html.erb
<!-- Category  Selection -->
<div class="section" id="category">
	<h3>Category</h3>
	<i>coming soon</i>
</div>

src/api/app/views/webui/project/_delete_dialog.html.erb
  <div class="dialog darkgrey_box">
    <div class="box box-shadow">
      <h2 class="box-header">Delete Confirmation</h2>
      <div class="dialog-content">
        <p>Do you really want to delete <%= project_or_package_link project: @project.name %>?</p>

        <%= form_tag({:controller => 'project', :action => 'destroy'}, :method => 'delete') do %>
          <%= hidden_field_tag(:project, @project) %>
          <% if @linking_projects && @linking_projects.length > 0 %>
            <p>Other projects still have source links to this project:</p>
            <ul>
              <% @linking_projects.each do |link| %>
                <li><%= link_to(elide(link, 40), :controller => 'project', :action => 'show', :project => link) %></li>
              <% end %>
            </ul>
          <% end %>

          <%= render partial: '/webui/shared/dialog_action_buttons' %>
        <% end %>
      </div>
    </div>
  </div>

src/api/app/views/webui/project/_edit_comment.html.erb
<div>

<% if @error %>
  <%= sprite_tag 'dialog-warning' %>
  <%= @error %>
<% end %>

<%= show_status_comment( @comment, @package, true, [] ) %>

src/api/app/views/webui/project/_incident_request_dialog.html.erb
  <div class="dialog darkgrey_box">
    <div class="box box-shadow">
      <h2 class="box-header">Submit as Update</h2>
      <div class="dialog-content">
        <p>This will submit your project as a Maintenance Incident Request.</p>
        <%= form_tag({:controller => 'project', :action => 'new_incident_request'}, :method => :post) do %>
          <%= hidden_field_tag(:project, @project) %>
          <p>
            <%= label_tag(:sourceproject, 'Project submitted as Update:') %><br/>
            <%= text_field_tag(:sourceproject, format_projectname(@project.name, User.current.login), :size => 40, :disabled => true) %><br/>

            <%= label_tag(:sourceproject, 'Release Targets:') %><br/>
            <% @releasetargets.each do |rt| %>
              <%= text_field_tag(:releasetarget, rt, :size=> 40, :disabled => true) %>
                <br/>
            <% end %>
            <%= label_tag(:description, 'Description:') %><br/>
            <%= text_area_tag(:description, '', :size => '40x3') %>
          </p>
          <%= render partial: '/webui/shared/dialog_action_buttons' %>
        <% end %>
      </div>
    </div>
  </div>

src/api/app/views/webui/project/_incident_table_entries.html.erb
<% incidents.each do |incident| %>
    <% index = 0 %>
    <% release_targets_ng = incident.release_targets_ng() %>
    <% release_targets_ng.each do |rt_name, rt| %>
        <tr>
          <% if index == 0 %>
              <td rowspan="<%= release_targets_ng.length %>">
                <% title = rt[:patchinfo].try(:[], :summary) || incident.title || incident.name %>
                <% title = "#{short_incident_name(incident)}: #{title}" %>
                <%= link_to(elide(title, 60, :right), project_show_path(project: incident.name), title: title) %>
              </td>
              <td rowspan="<%= release_targets_ng.length %>">
                <% if rt[:patchinfo] %>
                    <%= link_to(rt[:patchinfo][:category],
                          patchinfo_show_path(project: incident.name, package: "patchinfo", file: "_patchinfo"),
                          { style: "color: #{patchinfo_category_color(rt[:patchinfo][:category])};" }) %>
                <% else %>
                    <%= link_to(sprited_text('exclamation', 'Missing patchinfo'),
                          patchinfo_new_patchinfo_path(project: incident.name, package: "patchinfo"),
                          { style: 'color: red;', method: :post }) %>
                <% end %>
              </td>
              <td rowspan="<%= release_targets_ng.length %>">
                  <% unless rt[:packages].blank? %>
                    <% first_pkg = rt[:packages].first %>
                    <%= link_to(first_pkg.name.split('.', 2)[0], package_show_path(project: incident.name, package: first_pkg.name)) %>
                    <% if rt[:packages].length > 1 %>
                        , ...
                    <% end %>
                <% end %>
              </td>
              <td rowspan="<%= release_targets_ng.length %>" class="nowrap">
                <% rqs_in = BsRequest.list_numbers(roles: %w(target), states: %w(new review), project: incident.name) %>
                <% if rqs_in.count > 0 %>
                    <% if rqs_in.count == 1 %>
                        <% path = request_show_path(rqs_in.first) %>
                    <% else %>
                        <% path = project_requests_path(project: incident.name) %>
                    <% end %>
                    <%= link_to(sprite_tag('exclamation', title: pluralize(rqs_in.count, "open request")), path) %>
                <% end %>
                <% requests_out = BsRequest.list(roles: %w(source), states: %w(new review declined),
                                                          types: %w(maintenance_release), project: incident.name) %>
                <% if requests_out.present? %>
                    <% requests_out.sort {|x,y| x.number <=> y.number}.each do |rq_out| %>
                        <% text = "Release request in state '#{rq_out['state']}'" %>
                        <%= link_to(sprite_tag(map_request_state_to_flag(rq_out['state'].to_s), title: text),
                              request_show_path(rq_out["number"])) %>
                    <% end %>
                <% else %>
                    <% if incident.is_locked? %>
                        <%= sprite_tag('lock', title: 'Locked') %>
                    <% end %>
                <% end %>
                <% if rt[:patchinfo] && rt[:patchinfo][:stopped].present? %>
                    <%= sprite_tag("clock", title: "Stopped: #{rt[:patchinfo][:stopped]}") %>
                <% end %>
              </td>
          <% end %>
          <td><b><%= rt_name %></b></td>
          <td>
            <% buildresult_css_id = "incident_#{valid_xml_id(incident.name)}_results_#{valid_xml_id(rt_name)}" %>
            <% if incident.build_succeeded?(rt[:reponame]) %>
                <%= link_to(sprite_tag('tick', title: 'Build results', id: buildresult_css_id), project_show_path(project: incident.name)) %>
            <% else %>
                <%= link_to(sprite_tag('exclamation', title: 'Build results', id: buildresult_css_id), project_show_path(project: incident.name)) %>
            <% end %>
            <%= javascript_tag do %>
                setup_buildresult_tooltip('<%= buildresult_css_id %>',
                '<%= url_for(project_buildresult_path(project: incident.name)) %>');
            <% end %>
          </td>
          <% index += 1 %>
        </tr>
    <% end %>
<% end %>

src/api/app/views/webui/project/_packages_table.html.erb
<% content_for :ready_function do %>
    $( "#packages" ).tabs();
<% end %>

<div class="grid_10 alpha box box-shadow">

  <div id="packages">
    <div class="box-header header-tabs">
      <ul>
        <li><a href="#raw_packages" title="Packages directly in the project">Packages (<%= @packages.length %>)</a>
        </li>
        <% if @ipackages.present? %>
            <li>
              <a href="#inherited_packages"
                 title="Inherited Packages">Inherited Packages (<%= @ipackages.length %>)</a>
            </li>
        <% end %>
      </ul>
    </div>
    <div id="raw_packages" class="tab">

      <% packageurl = url_for(controller: 'package', action: 'show', project: @project, package: 'REPLACEIT') %>
      <% if @packages.present? %>
          <% cache [packageurl, Digest::MD5.hexdigest(@packages.join)] do %>
              <div id="packages_table_wrapper" data-url="<%= packageurl %>">
                <%= javascript_tag do %>
                    var packages = [ <%= escape_nested_list(@packages) %> ];
                    renderPackagesTable("packages_table_wrapper", packages);
                <% end %>
              </div>
          <% end %>
      <% else %>
          <p><i>This project does not contain any packages</i></p>
      <% end %>

      <% if @project.kind_of?(Project) && User.current.can_modify_project?(@project) %>
          <% if !@project.defines_remote_instance? && !(@is_incident_project && !@packages.blank? && @has_patchinfo && @open_release_requests.empty?) && !@is_maintenance_project %>
              <ul class="horizontal-list">
                <li>
                  <%= link_to(sprited_text('package_add', 'Create package'), controller: 'project', action: 'new_package', project: @project) %>
                </li>
                <li>
                  <%= link_to sprited_text('package_link', 'Branch existing package'), controller: :project, action: :new_package_branch, project: @project %>
                </li>
              </ul>
          <% end %>
      <% end %>
    </div>

    <% if @ipackages.present? %>
        <div id="inherited_packages" class="tab">
          <% packageurl = url_for(controller: 'package', action: 'show', project: @project, package: 'REPLACEPKG') %>
          <% cache [packageurl, Digest::MD5.hexdigest(@ipackages.join)] do %>
              <div id="ipackages_wrapper" data-url="<%= packageurl %>">
                <%= javascript_tag do %>
                    var ipackages = [ <%= escape_nested_list(@ipackages) %> ];
                    renderPackagesProjectsTable({packages: ipackages, name: 'ipackages_wrapper'});
                <% end %>
              </div>
          <% end %>
        </div>
    <% end %>

    <% if @packages.present? && @ipackages.present? %>
      <%= javascript_tag do %>
        $('#packages_table_wrapper_table_filter input:first-of-type').on("keyup paste", function() {
          $('#ipackages_wrapper_table').dataTable().fnFilter( $(this).val());
        });

        $('#ipackages_wrapper_table_filter input:first-of-type').on("keyup paste", function() {
          $('#packages_table_wrapper_table').dataTable().fnFilter( $(this).val());
        });
      <% end %>
    <% end %>
  </div>
  <% if @packages.present? && @ipackages.present? %>
    <%= javascript_tag do %>
        $('#packages_table_wrapper_table_filter input:first-of-type').on("keyup paste", function() {
          $('#ipackages_wrapper_table').dataTable().fnFilter( $(this).val());
        });
        $('#ipackages_wrapper_table_filter input:first-of-type').on("keyup paste", function() {
          $('#packages_table_wrapper_table').dataTable().fnFilter( $(this).val());
        });
    <% end %>
  <% end %>
  <noscript>
    <%= link_to 'Packages', action: 'packages_simple', project: @project %>
  </noscript>
</div>

src/api/app/views/webui/project/users.html.erb
<% @pagetitle = "Users of #{@project}"
   project_bread_crumb 'Users'
-%>

<%= render :partial => 'tabs' %>
<%= render :partial => "shared/involved_users" %>