src/api/config/routes.rb
# we take everything here that is not XML - the default mimetype is xml though
class WebuiMatcher
  class InvalidRequestFormat < APIException
  end

  def self.matches?(request)
    request.format.to_sym != :xml
  rescue ArgumentError => e
    raise InvalidRequestFormat, e.to_s
  end
end

# here we take everything that is XML, JSON or osc ;)
class APIMatcher
  def self.matches?(request)
    format = request.format.to_sym || :xml
    format == :xml || format == :json || public_or_about_path?(request)
  end

  def self.public_or_about_path?(request)
    request.fullpath.start_with?('/public', '/about')
  end
end

OBSApi::Application.routes.draw do
  mount Peek::Railtie => '/peek'

  cons = {
    arch:         %r{[^\/]*},
    binary:       %r{[^\/]*},
    filename:     %r{[^\/]*},
    id:           %r{\d*},
    login:        %r{[^\/]*},
    package:      %r{[^\/]*},
    package_name: %r{[^\/]*},
    project:      %r{[^\/]*},
    project_name: %r{[^\/]*},
    repository:   %r{[^\/]*},
    service:      %r{\w[^\/]*},
    title:        %r{[^\/]*},
    user:         %r{[^\/]*}
  }

  constraints(WebuiMatcher) do
    root 'webui/main#index'

    controller 'webui/main' do
      get 'main/systemstatus' => :systemstatus
      get 'main/add_news_dialog' => :add_news_dialog
      post 'main/add_news' => :add_news
      get 'main/delete_message_dialog' => :delete_message_dialog
      post 'main/delete_message' => :delete_message
    end

    controller 'webui/feeds' do
      get 'main/news' => :news, constraints: ->(req) { req.format == :rss }, as: :news_feed
      get 'main/latest_updates' => :latest_updates, constraints: ->(req) { req.format == :rss }, as: :latest_updates_feed
      get 'project/latest_commits/:project' => :commits, defaults: { format: 'atom' }, constraints: cons, as: 'commits_feed'
      get 'user/feed/:token' => :notifications, defaults: { format: 'rss' }, as: :user_rss_notifications
    end

    resources :attribs, constraints: cons, only: [:create, :update, :destroy], controller: 'webui/attribute' do
      collection do
        get ':project(/:package)/new' => :new, constraints: cons, as: 'new'
        get ':project(/:package)/:attribute/edit' => :edit, constraints: cons, as: 'edit'
        get ':project(/:package)' => :index, constraints: cons, as: 'index', defaults: { format: 'html' }
      end
    end

    resources :image_templates, constraints: cons, only: [:index], controller: 'webui/image_templates'

    resources :download_repositories, constraints: cons, only: [:create, :update, :destroy], controller: 'webui/download_on_demand'

    controller 'webui/configuration' do
      get 'configuration' => :index
      patch 'configuration' => :update
      get 'configuration/interconnect' => :interconnect
      post 'configuration/interconnect' => :create_interconnect
    end

    controller 'webui/subscriptions' do
      get 'notifications' => :index
      put 'notifications' => :update
    end

    controller 'webui/architectures' do
      get 'architectures' => :index
      patch 'architectures/bulk_update_availability' => :bulk_update_availability, as: 'bulk_update_availability'
    end

    controller 'webui/monitor' do
      get 'monitor/' => :index
      get 'monitor/old' => :old
      get 'monitor/update_building' => :update_building
      get 'monitor/events' => :events
    end

    defaults format: 'html' do
      controller 'webui/package' do
        get 'package/show/:project/:package' => :show, as: 'package_show', constraints: cons
        get 'package/dependency/:project/:package' => :dependency, constraints: cons
        get 'package/binary/:project/:package' => :binary, constraints: cons, as: 'package_binary'
        get 'package/binaries/:project/:package' => :binaries, constraints: cons, as: 'package_binaries'
        get 'package/users/:project/:package' => :users, as: 'package_users', constraints: cons
        get 'package/requests/:project/:package' => :requests, as: 'package_requests', constraints: cons
        get 'package/statistics/:project/:package' => :statistics, as: 'package_statistics', constraints: cons
        get 'package/commit/:project/:package' => :commit, as: 'package_commit', constraints: cons
        get 'package/revisions/:project/:package' => :revisions, constraints: cons, as: 'package_view_revisions'
        post 'package/submit_request/:project/:package' => :submit_request, constraints: cons
        get 'package/add_person/:project/:package' => :add_person, constraints: cons
        get 'package/add_group/:project/:package' => :add_group, constraints: cons
        get 'package/rdiff/:project/:package' => :rdiff, constraints: cons, as: 'package_rdiff'
        post 'package/save_new/:project' => :save_new, constraints: cons
        post 'package/branch' => :branch, constraints: cons
        post 'package/save/:project/:package' => :save, constraints: cons
        post 'package/remove/:project/:package' => :remove, constraints: cons
        get 'package/add_file/:project/:package' => :add_file, constraints: cons
        post 'package/save_file/:project/:package' => :save_file, constraints: cons
        post 'package/remove_file/:project/:package' => :remove_file, constraints: cons
        post 'package/save_person/:project/:package' => :save_person, constraints: cons
        post 'package/save_group/:project/:package' => :save_group, constraints: cons
        post 'package/remove_role/:project/:package' => :remove_role, constraints: cons
        get 'package/view_file/:project/:package/(:filename)' => :view_file, constraints: cons, as: 'package_view_file'
        get 'package/live_build_log/:project/:package/:repository/:arch' => :live_build_log, constraints: cons, as: 'package_live_build_log'
        defaults format: 'js' do
          get 'package/linking_packages/:project/:package' => :linking_packages, constraints: cons
          get 'package/update_build_log/:project/:package/:repository/:arch' => :update_build_log, constraints: cons
          get 'package/submit_request_dialog/:project/:package' => :submit_request_dialog, constraints: cons
          get 'package/delete_dialog/:project/:package' => :delete_dialog, constraints: cons
          post 'package/trigger_rebuild/:project/:package' => :trigger_rebuild, constraints: cons
          get 'package/abort_build/:project/:package' => :abort_build, constraints: cons
          post 'package/trigger_services/:project/:package' => :trigger_services, constraints: cons
          delete 'package/wipe_binaries/:project/:package' => :wipe_binaries, constraints: cons
        end
        get 'package/devel_project/:project/:package' => :devel_project, constraints: cons
        get 'package/buildresult' => :buildresult, constraints: cons
        get 'package/rpmlint_result' => :rpmlint_result, constraints: cons
        get 'package/rpmlint_log' => :rpmlint_log, constraints: cons
        get 'package/meta/:project/:package' => :meta, constraints: cons, as: 'package_meta'
        post 'package/save_meta/:project/:package' => :save_meta, constraints: cons
        # compat route
        get 'package/attributes/:project/:package', to: redirect('/attribs/%{project}/%{package}'), constraints: cons
        get 'package/edit/:project/:package' => :edit, constraints: cons, as: :package_edit
        # compat routes
        get 'package/repositories/:project/:package', to: redirect('/repositories/%{project}/%{package}'), constraints: cons
        get 'package/import_spec/:project/:package' => :import_spec, constraints: cons
        # compat route
        get 'package/files/:project/:package' => :show, constraints: cons
      end
    end

    resources :packages, only: [], param: :name do
      resource :job_history, controller: 'webui/packages/job_history', only: [] do
        get '/:project/:repository/:arch' => :index, as: :index, constraints: cons
      end

      resource :build_reason, controller: 'webui/packages/build_reason', only: [] do
        get '/:project/:repository/:arch' => :index, as: :index, constraints: cons
      end
    end

    controller 'webui/patchinfo' do
      post 'patchinfo/new_patchinfo' => :new_patchinfo
      post 'patchinfo/updatepatchinfo' => :updatepatchinfo
      get 'patchinfo/edit_patchinfo' => :edit_patchinfo
      get 'patchinfo/show/:project/:package' => :show, as: 'patchinfo_show', constraints: cons, defaults: { format: 'html' }
      get 'patchinfo/read_patchinfo' => :read_patchinfo
      post 'patchinfo/save' => :save
      post 'patchinfo/remove' => :remove
      get 'patchinfo/new_tracker' => :new_tracker
      get 'patchinfo/delete_dialog' => :delete_dialog
    end
    #
    controller 'webui/repositories' do
      get 'repositories/:project(/:package)' => :index, constraints: cons, as: 'repositories', defaults: { format: 'html' }
      get 'project/repositories/:project' => :index, constraints: cons, as: 'project_repositories'
      get 'project/add_repository/:project' => :new, constraints: cons
      get 'project/add_repository_from_default_list/:project' => :distributions, constraints: cons, as: :repositories_distributions
      post 'project/save_repository' => :create
      post 'project/update_target/:project' => :update, constraints: cons
      get 'project/repository_state/:project/:repository' => :state, constraints: cons, as: 'project_repository_state'
      post 'project/remove_target' => :destroy
      post 'project/create_dod_repository' => :create_dod_repository
      post 'project/create_image_repository' => :create_image_repository

      # Flags
      put 'flag/:project(/:package)' => :toggle_flag, constraints: cons
      post 'flag/:project(/:package)' => :create_flag, constraints: cons
      delete 'flag/:project(/:package)/:flag' => :remove_flag, constraints: cons
    end

    controller 'webui/kiwi/images' do
      get 'package/:package_id/kiwi_images/import_from_package' => :import_from_package, as: 'import_kiwi_image'
    end

src/api/app/controllers/webui/apidocs_controller.rb
class Webui::ApidocsController < Webui::WebuiController
  def index
    filename = File.expand_path(CONFIG['apidocs_location']) + '/index.html'
    if File.exist?(filename)
      render file: filename, formats: [:html]
    else
      logger.error "Unable to load apidocs index file from #{CONFIG['apidocs_location']}. Did you create the apidocs?"
      flash[:error] = 'Unable to load API documentation.'
      redirect_back(fallback_location: root_path)
    end
  end

  def file
    # Ensure it really is just a file name, no '/..', etc.
    filename = File.basename(params[:filename])
    file = File.expand_path(File.join(CONFIG['schema_location'], filename))
    if File.exist?(file)
      send_file(file, type: 'text/xml', disposition: 'inline')
    else
      flash[:error] = "File not found: #{params[:filename]}"
      redirect_back(fallback_location: { controller: 'apidocs', action: 'index' })
    end
    return
  end
end

src/api/app/controllers/webui/architectures_controller.rb
# Enabling/Disabling default architectures
class Webui::ArchitecturesController < Webui::WebuiController
  before_action :require_admin

  def index
    @architectures = Architecture.order(:name)
  end

  def bulk_update_availability
    all_valid = true
    params[:archs].each do |name, value|
      arch = Architecture.find_by(name: name)
      arch.available = value
      all_valid &&= arch.save
    end

    ::Configuration.write_to_backend

    respond_to do |format|
      if all_valid
        format.html { redirect_to architectures_path, notice: 'Architectures successfully updated.' }
      else
        format.html { redirect_back(fallback_location: root_path, error: 'Not all architectures could be saved') }
      end
    end
  end
end

src/api/app/controllers/webui/attribute_controller.rb
class Webui::AttributeController < Webui::WebuiController
  helper :all
  before_action :set_container, only: [:index, :new, :edit]
  before_action :set_attribute, only: [:update, :destroy]

  # raise an exception if authorize has not yet been called.
  after_action :verify_authorized, except: :index

  helper 'webui/project'

  def index
    @attributes = @container.attribs
  end

  def new
    if @package
      @attribute = Attrib.new(package_id: @package.id)
    else
      @attribute = Attrib.new(project_id: @project.id)
    end
    authorize @attribute, :create?
  end

  def edit
    @attribute = Attrib.find_by_container_and_fullname(@container, params[:attribute])

    authorize @attribute

    return unless @attribute.attrib_type.value_count && (@attribute.attrib_type.value_count > @attribute.values.length)
    (@attribute.attrib_type.value_count - @attribute.values.length).times { @attribute.values.build(attrib: @attribute) }
  end

  def create
    @attribute = Attrib.new(attrib_params)

    authorize @attribute

    # build the default values
    if @attribute.attrib_type.value_count
      @attribute.attrib_type.value_count.times do
        @attribute.values.build(attrib: @attribute)
      end
    end

    if @attribute.save
      if @attribute.values_editable?
        redirect_to edit_attribs_path(project: @attribute.project.to_s, package: @attribute.package.to_s,
                                      attribute: @attribute.fullname),
                    notice: 'Attribute was successfully created.'
      else
        redirect_to index_attribs_path(project: @attribute.project.to_s, package: @attribute.package.to_s),
                    notice: 'Attribute was successfully created.'
      end
    else
      redirect_back(fallback_location: root_path, error: "Saving attribute failed: #{@attribute.errors.full_messages.join(', ')}")
    end
  end

  def update
    authorize @attribute

    if @attribute.update(attrib_params)
      redirect_to edit_attribs_path(project: @attribute.project.to_s, package: @attribute.package.to_s, attribute: @attribute.fullname),
                  notice: 'Attribute was successfully updated.'
    else
      redirect_back(fallback_location: root_path, error: "Updating attribute failed: #{@attribute.errors.full_messages.join(', ')}")
    end
  end

  def destroy
    authorize @attribute

    @attribute.destroy
    redirect_back(fallback_location: root_path, notice: 'Attribute sucessfully deleted!')
  end

  private

  def set_container
    required_parameters :project
    begin
      @project = Project.get_by_name(params[:project])
    rescue APIException
      flash[:error] = "Project not found: #{params[:project]}"
      redirect_to(controller: 'project') && return
    end
    if params[:package]
      begin
        @package = Package.get_by_project_and_name(params[:project], params[:package], use_source: false)
      rescue APIException
        redirect_to(project_show_path(@project.to_s), error: "Package #{params[:package]} not found") && (return)
      end
      @container = @package
    else
      @container = @project
    end
  end

  def set_attribute
    @attribute = Attrib.find(params[:id])
    if @attribute.container.instance_of? Package
      @package = @attribute.container
      @project = @package.project
    elsif @attribute.container.instance_of? Project
      @project = @attribute.container
    end
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def attrib_params
    params.require(:attrib).permit(:attrib_type_id, :project_id, :package_id,
                                   values_attributes: [:id, :value, :position, :_destroy],
                                   issues_attributes: [:id, :name, :issue_tracker_id, :_destroy])
  end
end

src/api/app/controllers/webui/cloud/configurations_controller.rb
module Webui
  module Cloud
    class ConfigurationsController < WebuiController
      before_action :set_breadcrumb

      def index
        @crumb_list.push << 'Configuration'
      end

      private

      def set_breadcrumb
        @crumb_list = [WebuiController.helpers.link_to('Cloud Upload', cloud_upload_index_path)]
      end
    end
  end
end

src/api/app/controllers/webui/cloud/ec2/configurations_controller.rb
module Webui
  module Cloud
    module Ec2
      class ConfigurationsController < WebuiController
        before_action :require_login
        before_action :set_breadcrumb
        before_action -> { feature_active?(:cloud_upload) }

        def show
          @crumb_list << 'EC2'
          @ec2_configuration = User.current.ec2_configuration || User.current.create_ec2_configuration
          @aws_account_id = CONFIG['aws_account_id']
        end

        def update
          @ec2_configuration = User.current.ec2_configuration
          if @ec2_configuration.update(permitted_params)
            flash[:success] = 'Successfully updated your EC2 configuration.'
            redirect_to cloud_upload_index_path
          else
            flash[:error] = "Failed to updated your EC2 configuration: #{@ec2_configuration.errors.full_messages.to_sentence}."
            redirect_back(fallback_location: root_path)
          end
        end

        private

        def set_breadcrumb
          @crumb_list = [
            WebuiController.helpers.link_to('Cloud Upload', cloud_upload_index_path),
            WebuiController.helpers.link_to('Configuration', cloud_configuration_index_path)
          ]
        end

        def permitted_params
          params.require(:ec2_configuration).permit(:id, :arn)
        end
      end
    end
  end
end

src/api/app/controllers/webui/image_templates_controller.rb
class Webui::ImageTemplatesController < Webui::WebuiController
  before_action -> { feature_active?(:image_templates) }

  def index
    @projects = Project.image_templates

    respond_to do |format|
      format.html
      format.xml
    end
  end
end

src/api/app/views/webui/attribute/_attributes.html.haml
- if @attributes.blank?
  %p
    %em No attributes set
- else
  %div
    %table
      %tr
        %th Attribute
        %th Values
        - unless User.current.is_nobody?
          %th Actions
      - @attributes.each do |attribute|
        %tr.attribute-values
          %td{ class: "#{attribute.namespace}-#{attribute.name}" }
            = attribute.fullname
          %td{ class: "#{attribute.namespace}-#{attribute.name}-values" }
            = attribute.values.map(&:value).join(', ')
            = attribute.issues.map(&:name).join(', ')
          - unless User.current.is_nobody?
            %td
              = link_to(sprite_tag('note_edit', title: 'Edit values'),
                  edit_attribs_path(project: @project.name, package: @package, attribute: attribute.fullname),
                  class: 'edit-values') if attribute.values_editable?
              = button_to('Delete attribute', attrib_path(attribute),
                  { data: { confirm: "Really remove attribute '#{attribute.fullname}'?" },
                  method: :delete, class: 'delete-attribute', id: "#{attribute.namespace}-#{attribute.name}-delete", title: "Delete" })
- unless User.current.is_nobody?
  %p
    = link_to(sprited_text('note_add', 'Add a new attribute'),
        new_attribs_path(project: @project.name, package: @package),
        id: 'add-new-attribute')

src/api/app/views/webui/attribute/_form.html.haml
= form_for(@attribute) do |attribute_form|
  - if @attribute.errors.any?
    #error-explanation
      %h2
        = pluralize(@attribute.errors.count, "error")
        prohibited this attribute from being saved:
      %ul
        - @attribute.errors.full_messages.each do |message|
          %li
            = message
  #values
    = attribute_form.fields_for :values do |value|
      = render 'value_fields', f: value
    - if @attribute.values_addable?
      .links
        %p
          = link_to_add_association 'add value', attribute_form, :values
  - if @attribute.attrib_type.issue_list
    #issues
      = attribute_form.fields_for :issues do |issue|
        = render 'issue_fields', f: issue
    .links
      = link_to_add_association 'add issue', attribute_form, :issues
  .actions
    = attribute_form.hidden_field(:attrib_type_id)
    %p
      = attribute_form.submit "Save Attribute"

src/api/app/views/webui/attribute/_issue_fields.html.haml
.nested-fields
  .field
    = f.select :issue_tracker_id, IssueTracker.all.collect { |tracker| [tracker.name, tracker.id] }.sort, include_blank: false
    = f.label :id
    = f.text_field :name
    = link_to_remove_association "remove issue", f

src/api/app/views/webui/attribute/_value_fields.html.haml
.nested-fields
  .field
    %p
      - if @attribute.values_addable?
        = f.label :position
        = f.number_field :position, class: "attrib-position-input", size: 3
      = f.label :value
      - if @attribute.attrib_type.allowed_values.any?
        = f.select :value, @attribute.attrib_type.allowed_values.map(&:value), { include_blank: false }, { id: 'attrib-default-select' }
      - else
        = f.text_field :value
      - if @attribute.values_removeable?
        = link_to_remove_association "remove value", f

src/api/app/views/webui/attribute/edit.html.haml
- @pagetitle = "Edit Attribute #{@attribute.fullname} on #{@container.class} #{@container.name}"
- project_bread_crumb
- if @package
  - @crumb_list << link_to(@package, package_show_path(package: @package))
  - @crumb_list << link_to('Attributes', index_attribs_path(project: @project.name, package: @package))
- else
  - @crumb_list << link_to('Attributes', index_attribs_path(project: @project.name))
- @crumb_list << @attribute.fullname
- if @package
  = render partial: "webui/package/tabs"
- else
  = render partial: "webui/project/tabs"
%h2
  = @pagetitle
%p
  = @attribute.attrib_type.description
- if @attribute.values_editable?
  = render 'form'
- else
  %p
    This attribute has no values to edit

src/api/app/views/webui/attribute/index.html.haml
- @pagetitle = "Attributes"
- project_bread_crumb
- if @package
  - @crumb_list << link_to(@package, package_show_path(package: @package))
- @crumb_list << "Attributes"
- if @package
  = render partial: "webui/package/tabs"
- else
  = render partial: "webui/project/tabs"
= render partial: "attributes"

src/api/app/views/webui/attribute/new.html.haml
- @pagetitle = "Add Attribute"
- project_bread_crumb
- if @package
  - @crumb_list << link_to(@package, package_show_path(package: @package))
  - @crumb_list << link_to('Attributes', index_attribs_path(project: @project.name, package: @package))
- else
  - @crumb_list << link_to('Attributes', index_attribs_path(project: @project.name))
- @crumb_list << "Add"
- if @package
  = render partial: "webui/package/tabs"
- else
  = render partial: "webui/project/tabs"
%h2
  = @pagetitle
= form_for(@attribute) do |f|
  .field
    %p
      = f.select :attrib_type_id, AttribType.all.collect { |a| [a.fullname, a.id] }.sort, include_blank: false
      = hidden_field_tag("attrib[project_id]", @attribute.project_id)
      = hidden_field_tag("attrib[package_id]", @attribute.package_id) if @attribute.package_id
  %p.help-block#first-help
    = AttribType.all.to_a.sort_by { |t| t.fullname }.first.description
    = "Sorry, this attribute has no description" if AttribType.all.to_a.sort_by { |t| t.fullname }.first.description.blank?
  - AttribType.all.each do |type|
    %p.help-block.attrib-type{ id: "#{type.id}-help" }
      = type.description
      = "Sorry, this attribute has no description" if type.description.blank?
  .actions
    %p
      = f.submit "Create Attribute"